{
  flake-parts-lib,
  lib,
  ...
}: let
  inherit (lib) mkOption types literalExpression;

  # Import type definitions
  workflowTypes = import ./types/workflow.nix {inherit lib;};
  inherit (workflowTypes) workflowType;

  actionTypes = import ./types/action.nix {inherit lib;};
  inherit (actionTypes) actionType;

  # Import conversion functions
  converters = import ./converters.nix {inherit lib;};
  inherit (converters) workflowToYaml actionToYaml;
in {
  options.perSystem = flake-parts-lib.mkPerSystemOption (
    psArgs @ {pkgs, ...}: let
      cfg = psArgs.config.githubActions;
    in {
      options = {
        githubActions = {
          enable = mkOption {
            type = types.bool;
            default = false;
            description = "Whether to generate GitHub Actions workflows from Nix configuration.";
          };

          workflows = mkOption {
            type = types.attrsOf workflowType;
            default = {};
            description = ''
              GitHub Actions workflows to generate. Keys are workflow file names
              (without the .yml extension).
            '';
            example = literalExpression ''
              {
                ci = {
                  name = "CI";
                  on = ["push" "pull_request"];
                  jobs = {
                    build = {
                      runsOn = "ubuntu-latest";
                      steps = [
                        {
                          uses = "actions/checkout@v4";
                        }
                        {
                          name = "Build";
                          run = "npm run build";
                        }
                      ];
                    };
                  };
                };
              }
            '';
          };

          workflowsDir = mkOption {
            type = types.package;
            readOnly = true;
            description = ''
              Generated .github/workflows directory as a derivation.
              Contains all workflow files defined in the configuration.
              Only populated when `enable = true`.
            '';
          };

          workflowFiles = mkOption {
            type = types.attrsOf types.package;
            readOnly = true;
            description = ''
              Individual workflow files as derivations.
              Keys are workflow names (without .yml extension).
              Only populated when `enable = true`.
            '';
          };

          actions = mkOption {
            type = types.attrsOf actionType;
            default = {};
            description = ''
              GitHub actions to generate. Keys are action names;
              each emits .github/actions/<name>/action.yml.
            '';
            example = literalExpression ''
              {
                setup-ci = {
                  name = "Setup CI";
                  description = "Checkout + toolchain setup";
                  runs.steps = [
                    { uses = "actions/checkout@v4"; }
                    { name = "Install"; run = "npm ci"; }
                  ];
                };
              }
            '';
          };

          actionFiles = mkOption {
            type = types.attrsOf types.package;
            readOnly = true;
            description = ''
              Individual composite action files as derivations.
              Keys are "<name>/action.yml". Only populated when enable = true.
            '';
          };

          actionsDir = mkOption {
            type = types.package;
            readOnly = true;
            description = ''
              Generated .github/actions directory as a derivation, containing
              <name>/action.yml subdirectories. Only populated when enable = true.
            '';
          };
        };
      };

      config = let
        # Generate individual workflow files
        workflowFiles =
          lib.mapAttrs' (
            name: workflow:
              lib.nameValuePair "${name}.yml" (
                pkgs.runCommandLocal "${name}.yml" {
                  nativeBuildInputs = [pkgs.yq-go];
                  json = builtins.toJSON (workflowToYaml workflow);
                  passAsFile = ["json"];
                } ''
                  {
                    echo "# This file is automatically generated from Nix configuration. Do not edit directly."
                    echo ""
                    yq eval --prettyPrint '.' -P $jsonPath
                  } > $out
                ''
              )
          )
          cfg.workflows;

        # Generate individual composite action files (directory per action)
        actionFiles =
          lib.mapAttrs' (
            name: action:
              lib.nameValuePair "${name}/action.yml" (
                pkgs.runCommandLocal "${name}-action.yml" {
                  nativeBuildInputs = [pkgs.yq-go];
                  json = builtins.toJSON (actionToYaml action);
                  passAsFile = ["json"];
                } ''
                  {
                    echo "# This file is automatically generated from Nix configuration. Do not edit directly."
                    echo ""
                    yq eval --prettyPrint '.' -P $jsonPath
                  } > $out
                ''
              )
          )
          cfg.actions;
      in {
        githubActions = {
          workflowFiles = lib.mkIf cfg.enable workflowFiles;

          workflowsDir = lib.mkIf cfg.enable (
            # Create a directory with all workflow files
            pkgs.runCommandLocal "github-workflows" {} ''
              mkdir -p $out
              ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: file: ''
                  cp ${file} $out/${name}
                '')
                workflowFiles)}
            ''
          );

          actionFiles = lib.mkIf cfg.enable actionFiles;

          actionsDir = lib.mkIf cfg.enable (
            # Create a directory with all composite action subdirectories
            pkgs.runCommandLocal "github-actions-composite" {} ''
              mkdir -p $out
              ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: file: ''
                  mkdir -p "$out/$(dirname ${name})"
                  cp ${file} $out/${name}
                '')
                actionFiles)}
            ''
          );
        };
      };
    }
  );
}
