{
  flake-parts-lib,
  lib,
  ...
}: let
  inherit (lib) mkOption types literalExpression;

  # Import type definitions
  workflowTypes = import ./types/workflow.nix {inherit lib;};
  inherit (workflowTypes) workflowType;

  # Import conversion functions
  converters = import ./converters.nix {inherit lib;};
  inherit (converters) workflowToYaml;
in {
  options.perSystem = flake-parts-lib.mkPerSystemOption (
    psArgs @ {pkgs, ...}: let
      cfg = psArgs.config.githubActions;
    in {
      options = {
        githubActions = {
          enable = mkOption {
            type = types.bool;
            default = false;
            description = "Whether to generate GitHub Actions workflows from Nix configuration.";
          };

          workflows = mkOption {
            type = types.attrsOf workflowType;
            default = {};
            description = ''
              GitHub Actions workflows to generate. Keys are workflow file names
              (without the .yml extension).
            '';
            example = literalExpression ''
              {
                ci = {
                  name = "CI";
                  on = ["push" "pull_request"];
                  jobs = {
                    build = {
                      runsOn = "ubuntu-latest";
                      steps = [
                        {
                          uses = "actions/checkout@v4";
                        }
                        {
                          name = "Build";
                          run = "npm run build";
                        }
                      ];
                    };
                  };
                };
              }
            '';
          };

          workflowsDir = mkOption {
            type = types.package;
            readOnly = true;
            description = ''
              Generated .github/workflows directory as a derivation.
              Contains all workflow files defined in the configuration.
            '';
          };

          workflowFiles = mkOption {
            type = types.attrsOf types.package;
            readOnly = true;
            description = ''
              Individual workflow files as derivations.
              Keys are workflow names (without .yml extension).
            '';
          };
        };
      };

      config = let
        # Generate individual workflow files
        workflowFiles =
          lib.mapAttrs' (
            name: workflow:
              lib.nameValuePair "${name}.yml" (
                pkgs.runCommand "${name}.yml" {
                  nativeBuildInputs = [pkgs.yq-go];
                  json = builtins.toJSON (workflowToYaml workflow);
                  passAsFile = ["json"];
                } ''
                  {
                    echo "# This file is automatically generated from Nix configuration. Do not edit directly."
                    echo ""
                    yq eval --prettyPrint '.' -P $jsonPath
                  } > $out
                ''
              )
          )
          cfg.workflows;
      in {
        githubActions.workflowFiles = lib.mkIf cfg.enable workflowFiles;

        githubActions.workflowsDir = lib.mkIf cfg.enable (
          # Create a directory with all workflow files
          pkgs.runCommand "github-workflows" {} ''
            mkdir -p $out
            ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: file: ''
                cp ${file} $out/${name}
              '')
              workflowFiles)}
          ''
        );
      };
    }
  );
}
